name: leafety
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.1+76

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.0.5
  cupertino_icons: ^0.1.3
  provider: ^5.0.0
  http: ^0.13.0
  socket_io_client: ^0.9.11
  carousel_slider: ^2.3.1
  font_awesome_flutter: 8.8.1
  flutter_svg: ^0.21.0+1
  rxdart: ^0.23.0
  image_picker: ^0.7.2+1
  flutter_bloc: ^7.0.0
  google_sign_in: ^5.0.1
  sign_in_with_apple: ^3.0.0
  mime_type:
  date_format: ^1.0.9
  flutter_masked_text: ^0.8.0
  intl: ^0.16.1
  flutter_slidable: ^0.5.7
  animations: ^1.1.2
  animate_do: ^1.7.5
  flutter_rating_bar: ^3.2.0+1
  like_button: ^2.0.1
  cached_network_image: ^2.1.0
  url_launcher: ^6.0.2
  pdf: ^3.2.0
  open_file: ^3.1.0
 
  universal_platform: ^0.1.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/leafety_icon.png"
    adaptive_icon_background: "assets/icon/leafety_icon.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
             
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/banners/
    - assets/images/
    - assets/onBoard/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
